#!/usr/bin/sh

## Configurations ##

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
    #bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' ' '

		let name++
	done
}
workspaces

bspc config border_width 2
bspc config window_gap 4
bspc config split_ratio 0.45
bspc config bottom_padding 1
bspc config left_padding 1
bspc config right_padding 1
#bspc config top_padding 1

bspc config normal_border_color "#2F3D44"
bspc config focused_border_color "#969696" 
#bspc config focused_border_color "#7FA094" 

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Rule Set ##

bspc rule -a Lxappearance state=floating
bspc rule -a File Transfer* state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a qt5ct state=floating
bspc rule -a mpv state=floating
#bspc rule -a Xfce4-power-manager-settings state=floating
#bspc rule -a Galculator state=floating
#bspc rule -a KeePassXC state=floating
#bspc rule -a Brave-browser state=fullscreen
#bspc rule -a Nitrogen state=floating
#bspc rule -a Pamac-manager state=floating

## Kill if already running ##

killall -9 xsettingsd unclutter xsetroot -cursor_name left_ptr picom gammastep sxhkd ksuperkey pulseaudio numlockx pgrep bspswallow $HOME/Public/scripts/bspswallow xwallpaper xset

## autostart ##

sxhkd &
pulseaudio &
exec mpd &
xset r rate 250 100 &
ff-theme-util &
$HOME/.config/polybar/launch.sh &
$HOME/Public/scripts/bspswallow &
xwallpaper --zoom $HOME/.config/nsxiv/wall &
picom &
fix_xcursor &
xsetroot -cursor_name left_ptr &
unclutter -idle 3 &
pgrep bspswallow || bspswallow &
xrdb ~/.config/x11/.Xresources &
#xbanish &
#lxqt-policykit-agent &
#nitrogen --restore &
#numlockx &
#dunst &
#nm-applet &
#betterlockscreen &
#xfce4-power-manager &

