#!/bin/sh

du -a  ~/.config/alacritty/* ~/.config/bspwm* ~/.config/gammastep* ~/.config/mpv* ~/.config/neofetch/* ~/.config/nvim/* ~/.config/polybar/* ~/.config/ranger/* ~/.config/sxhkd/* ~/.config/zsh-source/* ~/.config/picom.conf ~/Public/scripts* ~/.config/ncmpcpp ~/.config/mpd ~/.zshrc ~/.xinitrc ~/Downloads | awk '{print $2 }' | fzf --prompt="> Select a File or Script: " --reverse --border --multi --preview='head -$LINES {}' --height 70% | xargs -r $EDITOR
